# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('message', markdownx.models.MarkdownxField()),
            ],
        ),
    ]
