# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 21:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.SmallIntegerField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PopupPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pbcore_source', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
                ('state', localflavor.us.models.USStateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('collection_id', models.IntegerField()),
                ('name', models.TextField()),
                ('asset_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('transcript_data_blob', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_blob_processed', models.BooleanField(default=False)),
                ('metadata_processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=255, null=True)),
                ('broadcast_date', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='transcript.Transcript')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField()),
                ('text', models.TextField()),
                ('start_time', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_time', models.DecimalField(decimal_places=2, max_digits=12)),
                ('speaker_id', models.IntegerField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='transcript.Transcript')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptPhraseCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.CharField(blank=True, max_length=500, null=True)),
                ('no_words', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=-1.0)),
                ('appearances', models.IntegerField(default=0)),
                ('votes', models.IntegerField(default=0)),
                ('transcript_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_phrase_correction', to='transcript.TranscriptPhrase')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptPhraseDownvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.TranscriptPhrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='topic',
            name='transcripts',
            field=models.ManyToManyField(to='transcript.Transcript'),
        ),
        migrations.AddField(
            model_name='source',
            name='transcripts',
            field=models.ManyToManyField(to='transcript.Transcript'),
        ),
    ]
