# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 20:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptphrasecorrection',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
