# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-09 21:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='transcript_data_blob',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
