# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-10 20:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_auto_20161109_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
