# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0002_transcriptphrasecorrection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptmetadata',
            name='media_type',
            field=models.CharField(choices=[('v', 'Video'), ('a', 'Audio'), ('u', 'Unknown')], default='u', max_length=1),
        ),
    ]
