# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0004_auto_20161229_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptphrase',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
