# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0006_auto_20170227_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptphrasecorrectionvote',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
    ]
