# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0007_transcriptphrasecorrectionvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptphrase',
            name='num_corrections',
            field=models.SmallIntegerField(default=0),
        ),
    ]
