# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-08 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0008_transcriptphrase_num_corrections'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transcriptphrasecorrectionvote',
            unique_together=set([('user', 'transcript_phrase_correction')]),
        ),
    ]
