# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0011_auto_20170621_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptphrase',
            name='num_votes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
