# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcript', '0013_transcriptphrase_current_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptPhraseVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.NullBooleanField()),
                ('transcript_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcript.TranscriptPhrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
