# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0020_auto_20171103_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptphrasecorrectionvote',
            name='upvote',
            field=models.NullBooleanField(default=None),
        ),
    ]
