# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 18:41
from __future__ import unicode_literals

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist


def convert_self_votes_to_null(apps, schema_editor):
    TranscriptPhraseCorrection = apps.get_model(
        'transcript', 'TranscriptPhraseCorrection'
    )
    TranscriptPhraseCorrectionVote = apps.get_model(
        'transcript', 'TranscriptPhraseCorrectionVote'
    )
    for correction in TranscriptPhraseCorrection.objects.all():
        try:
            vote = TranscriptPhraseCorrectionVote.objects.get(
                user=correction.user,
                transcript_phrase_correction=correction
            )
            vote.upvote = None
            vote.save(update_fields=['upvote'])
        except ObjectDoesNotExist:
            TranscriptPhraseCorrectionVote.objects.create(
                user=correction.user,
                transcript_phrase_correction=correction,
                upvote=None
            )


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0021_auto_20171103_1822'),
    ]

    operations = [
        migrations.RunPython(convert_self_votes_to_null)
    ]
