# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0022_auto_20171103_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptphrasecorrectionvote',
            name='upvote',
            field=models.NullBooleanField(default=False),
        ),
    ]
