# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-08 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0024_auto_20180105_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptphrasecorrectionvote',
            name='original_phrase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript.TranscriptPhrase'),
        ),
    ]
