# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0025_transcriptphrasecorrectionvote_original_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
