# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0026_transcript_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptphrase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
