# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 20:14
from __future__ import unicode_literals

from django.db import migrations


def create_game_two_interactions(apps, schema_editor):
    TranscriptPhraseVote = apps.get_model(
        'transcript', 'TranscriptPhraseVote'
    )
    TranscriptPhraseCorrection = apps.get_model(
        'transcript', 'TranscriptPhraseCorrection'
    )
    TranscriptPhraseCorrectionVote = apps.get_model(
        'transcript', 'TranscriptPhraseCorrectionVote'
    )
    TranscriptPhraseInteraction = apps.get_model(
        'transcript', 'TranscriptPhraseInteraction'
    )
    ContentType = apps.get_model(
        'contenttypes', 'ContentType'
    )

    print(TranscriptPhraseInteraction.__dict__)

    for correction in TranscriptPhraseCorrection.objects.all():
        TranscriptPhraseInteraction.objects.create(
            transcript_phrase=correction.transcript_phrase,
            user=correction.user,
            preclude_from_game=2,
            content_type=ContentType.objects.get(
                app_label='transcript',
                model='transcriptphrasecorrection'
            ),
            object_id=correction.pk
        )

    for correction_vote in TranscriptPhraseCorrectionVote.objects.filter(upvote=True):
        TranscriptPhraseInteraction.objects.create(
            transcript_phrase=correction_vote.transcript_phrase_correction.transcript_phrase,
            user=correction_vote.user,
            preclude_from_game=2,
            content_type=ContentType.objects.get(
                app_label='transcript',
                model='transcriptphrasecorrectionvote'
            ),
            object_id=correction_vote.pk
        )

    for phrase_vote in TranscriptPhraseVote.objects.filter(upvote=True):
        TranscriptPhraseInteraction.objects.create(
            transcript_phrase=phrase_vote.transcript_phrase,
            user=phrase_vote.user,
            preclude_from_game=2,
            content_type=ContentType.objects.get(
                app_label='transcript',
                model='transcriptphrasevote'
            ),
            object_id=phrase_vote.pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0028_transcriptphraseinteraction'),
    ]

    operations = [
        migrations.RunPython(create_game_two_interactions)
    ]
