# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-15 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcript', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('considered_phrases', models.ManyToManyField(to='transcript.TranscriptPhrase')),
                ('preferred_stations', models.ManyToManyField(to='transcript.Source')),
                ('preferred_topics', models.ManyToManyField(to='transcript.Topic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
