# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-27 19:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161214_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('leaderboard', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
