# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcript', '0007_transcriptphrasecorrectionvote_upvote'),
        ('accounts', '0006_leaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='correction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript.TranscriptPhraseCorrection'),
        ),
        migrations.AddField(
            model_name='score',
            name='justification',
            field=models.CharField(choices=[(0, 'participation'), (1, 'correction confidence exceeds positive threshold'), (2, 'phrase confidence exceeds negative threshold'), (3, 'phrase confidence exceeds positive threshold')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='score',
            name='phrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transcript.TranscriptPhrase'),
        ),
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.CharField(choices=[(1, 'Identify Errors'), (2, 'Suggest Fixes'), (3, 'Validate Fixes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.SmallIntegerField(),
        ),
    ]
