# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 19:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_completed_challenges'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statistics', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
