# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contributionstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='considered_phrases',
        ),
    ]
